language: generic

env:
  global:
    - APM_TEST_PACKAGES=""

notifications:
  email:
    on_success: never
    on_failure: change

before_script:
  - npm install

script:
  - 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
  - chmod u+x build-package.sh
  - ./build-package.sh

branches:
  only:
    - master

git:
  depth: 10

sudo: false

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
